CREATE TABLE PROPRIETARIO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(60) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,

    PRIMARY KEY (ID)
);

ALTER TABLE PROPRIETARIO ADD CONSTRAINT UK_PROPRIETARIO_EMAIL UNIQUE (EMAIL);